name: deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version:  14.x
      - name: Install Dependency
        run: npm install
      - name: Build
        run: npm run build
      - name: change directory
        working-directory: dist
      - name: git add
        run: git add -A
      - name: git commit
        run: git commit -m 'deploy'
      - name: git push
        run: git push -f git@github.com:t6tg/ywc18-homework.git master:gh-pages
